// <auto-generated />
namespace tuc2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedteststableandmodifiedrelationships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedteststableandmodifiedrelationships));
        
        string IMigrationMetadata.Id
        {
            get { return "201901210945047_Added tests table and modified relationships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
