// <auto-generated />
namespace tuc2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SimplifiedinputandoutputexamplesinTestTaskstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SimplifiedinputandoutputexamplesinTestTaskstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201901201733145_Simplified input and output examples in TestTasks table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
